config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root to: 'pages#homepage'

  resources :items do
    post '/trade/:bid_id', on: :member, to: 'items#add_trade', as: 'add_trade'
    post '/cancel/:bid_id', on: :member, to: 'items#cancel_bid', as: 'cancel_bid'
    member do
      delete :delete_image_attachment
    end
  end

  get 'users/new'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 }, 
                        format: { with: VALID_EMAIL_REGEX },
                        uniqueness: { case_sensitive: false }

    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    has_many :items
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
            BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ItemsHelper
  def show 
    
      @user = User.find(params[:id])
      users_item = Item.where(["user_id = :id", {id: params[:id]}])
      @user_items = sorted_items(users_item)
    
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # handle a successful save.
      log_in @user
      flash[:success] = 'Welcome to SwapSpace!'
      redirect_to @user
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, size: 80)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: 'gravatar rounded-circle card-image-top')
    end
end

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<h1 class="text-center mt-5">Sign up</h1>

<div>
    <%= form_for(@user, url: signup_path) do |f| %>
        <%= render 'shared/error_messages' %>
        <div class="form-group">
            <%= f.text_field :name, class: 'form-control col-md-4 offset-md-4', placeholder: "Name"%>
        </div>
        <div class="form-group">
            <%= f.text_field :email, class: 'form-control col-md-4 offset-md-4', placeholder: "Email Address" %>
        </div>
        <div class="form-group">
            <%= f.password_field :password, class: 'form-control col-md-4 offset-md-4', placeholder: "Password" %>
        </div>
        <div class="form-group">
            <%= f.password_field :password_confirmation, class: 'form-control col-md-4 offset-md-4', placeholder: "Confirm Password" %>
        </div>
        <div class="form-group text-center">
            <button class="btn"><%= f.submit 'Create my account', class: "btn btn-outline-primary" %></button>
        </div>
    <% end %>
</div>

app/views/users/show.html.erb
<div class="card" style="width: 100%;">
  <div class="card-body">
    <% provide(:title, @user.name) %>
    <div class= "text-center">
      <%= gravatar_for @user %>
      <h5 class="card-title text-center mt-4"><%= @user.name %></h5>
      <p class="card-text text-center"><%= @user.email %></p>
    </div>
  </div>
</div>
<p>
<div class="text-center">
  <% if !@user_items.empty? %>
    <button class= "btn btn-outline-secondary dropdown-toggle " id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Sort By
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
      <li><%= link_to "Name", {:order => session[:order], :sort => "name",}, class: "dropdown-item" %></li>
      <li><%= link_to "Category", {:order => session[:order], :sort => "category",}, class: "dropdown-item" %></li>
      <li><%= link_to "Date", {:order => session[:order], :sort => "created_at",}, class: "dropdown-item" %></li>
      <li><%= link_to "Popularity", {:order => session[:order], :sort => "popularity",}, class: "dropdown-item" %></li>
    </div>
    <% if params["sort"].present? %>
      <% if params["order"] == "desc" %>
        <button  class= "btn" aria-haspopup="true" aria-expanded="false"><%= link_to "Ascending", {:order => "asc", :sort => params["sort"],},  class: "btn btn-outline-secondary" %></button>
      <% end %>
      <% if params["order"] == "asc" %>
        <button class="btn" aria-haspopup="true" aria-expanded="false"><%= link_to "Descending", {:order => "desc", :sort => params["sort"],}, class: "btn btn-outline-secondary" %></button>
      <% end %>
    <% end %>
  <% end %>
</div>

</p>

<!-- render a list of user's item -->
<div class="card" style="width: 100%;">
  <span class="text-center card-header bg-light navbar-brand mr-0">Items</span>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
      <% @user_items.each do |item| %>
        <% cache(item) do%>
          <% if !item.trade_established %>
            <div class="container">
              <div class="card mb-3 col-md-6 offset-md-3 pl-0 pr-0">
                <div class="row no-gutters">
                  <div class="col-md-4">
                    <% if !item.images.empty? %>
                      <div id='MyCarousel' class="carousel slide carousel-fade" data-ride="carousel">
                        <div class="carousel-inner" role="listbox">
                          <div class="carousel-item active card-img-left">
                            <%= image_tag(item.images.first, style: 'height: 100%; width: 100%; object-fit: contain') %>
                          </div>
                          <% item.images.drop(1).each do |photo| %>
                            <div class="carousel-item card-img-left">
                              <%= image_tag(photo, style: 'height: 100%; width: 100%; object-fit: contain') %>
                            </div>
                          <% end %>
                        </div>
                        <ol class="carousel-indicators">
                          <% item.images.each_with_index do |photo, n| %>
                            <li data-target='#MyCarousel' data-slide-to="#{n}" class="#{'active' if n == 0}"></li>
                          <% end %>
                        </ol>
                      </div>
                    <% end %>
                  </div>
                  <div class="col-md-8">
                    <div class="card-body">
                      <% provide(:title, item.name) %>
                      <h4 class="card-title"><%=  item.name %></h4>
                      <p class="card-text">Category: <%= item.category %></p>
                      <p class="card-text">User: <%= @user.name %></p>
                      <p class="card-text">Description: <%= item.description%></p>
                      <p class="card-text">Date Added: <%= item.created_at %></p>
                    
                      <%= pplrt=item.popularity %>
                      <%cache(pplrt) do %>
                        <p class="card-text">Popularity: <%= pplrt %></p>
                      <%end%>
                    </div>
                    <button class="btn ml-2" aria-haspopup="true" aria-expanded="false"><%= link_to 'Show', item, class: "btn btn-outline-primary" %></button>
                    <button class="btn" aria-haspopup="true" aria-expanded="false"><%= link_to 'Edit', edit_item_path(item), class: "btn btn-outline-primary" %></button>
                    <button class="btn" aria-haspopup="true" aria-expanded="false"><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %></button>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </li>
  </ul>
</div>

<p>
  <% if logged_in? %>
    <div class="card" style="width: 100%;">
      <span class="text-center card-header bg-light navbar-brand mr-0">Trade History</span>
      <table class="table">
        <tbody>
          <% User.find(params["id"]).items.each do |item| %>
            <% cache(item) do %>
              <tr>
                <% if item.trade_established %>
                  <td> <%= link_to "#{item.name}", item, class: "text-info" %> <td>
                  <th> Traded with </th>
                  <% item_traded = item.traded_item %>
                  <td> <%= link_to "#{item_traded.name}", item_traded, class: "text-info"  %> </td>
                  <th> Belonging To </th>
                  <% owner = User.find(item_traded.user_id) %>
                  <% cache(owner) do %>
                  <td> <%= link_to "#{owner.name}", owner, class: "text-info"  %> </td>
                  <th> at </th>
                  <% item_t = item.traded_item_time %>
                  <%cache(item_t) do %>
                  <% item_t_traded_with = item_traded.traded_item_time %>
                  <% cache (item_t_traded_with) do %>
                  <td> <%= item.compare(item_t['created_at'], item_t_traded_with['created_at'])%> </td>
                  <% end %>
                  <% end %>
                  <% end %>
                <% end %>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    <% end %>
</p>