config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root to: 'pages#homepage'

  resources :items do
    post '/trade/:bid_id', on: :member, to: 'items#add_trade', as: 'add_trade'
    post '/cancel/:bid_id', on: :member, to: 'items#cancel_bid', as: 'cancel_bid'
    member do
      delete :delete_image_attachment
    end
  end

  get 'users/new'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :user
    has_and_belongs_to_many :bid_by,
        class_name: 'Item',
        join_table: :trades,
        foreign_key: :item_id,
        association_foreign_key: :bid_by_item_id
    has_and_belongs_to_many :bid_for,
        class_name: 'Item',
        join_table: :trades,
        foreign_key: :bid_by_item_id,
        association_foreign_key: :item_id
    validates :description, length: { maximum: 1000 }
    validates :name, length: { maximum: 100 }

    has_many_attached :images
    def popularity
        return bid_by.count
    end

    def traded_item 
        # this should have length one
        traded_items = bid_by.select do |bidder|
            bid_for.include?(bidder)
        end
        return traded_items[0]
    end

    def traded_item_time
        sql = "SELECT created_at FROM trades WHERE item_id = #{id} LIMIT 1"
        records_array = ActiveRecord::Base.connection.execute(sql)
        return records_array[0]
    end

    def compare(a, b)
        return a < b ? b : a
    end

    def url(s)
        return puts("item/" + s.to_s)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy, :add_trade, :cancel_bid, :delete_image_attachment]
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]
  #before_action :establish, only:  [:add_trade]
  before_action :has_not_been_traded_assertion, only: [:edit, :update, :add_trade, :cancel_bid, :destroy]
  before_action :bid_has_not_been_traded_assertion, only: [:add_trade, :cancel_bid]

  # GET /items
  # GET /items.json
  def index
    item_per_page = 10
    page_num = params['page_num'].present? ? params['page_num'].to_i : 1
    
    #queried_items = sorted_items(
     # Item.where(trade_established: false)
     # )
     # .offset((page_num - 1) * item_per_page)
     # .limit(item_per_page + 1)
    queried_items=Rails.cache.fetch("querieditems", expires_in: 5.minutes) do
      sorted_items(
         Item.where(trade_established: false)
        )
        .offset((page_num - 1) * item_per_page)
        .limit(item_per_page + 1)
    end
    @prev_page = page_num == 1 ? nil : page_num - 1
    @next_page = queried_items.length <= item_per_page ? nil : page_num + 1
    @items = queried_items.limit(item_per_page)
  end

  # GET /items/1
  # GET /items/1.json
  def show
    session[:return_to] = request.referer
    if @item.trade_established 
      @traded_item = @item.traded_item
    end
  end

  # GET /items/new
  def new
    @item = Item.new(user_id: current_user.id)
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    @item.user = current_user

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render new_item_path, notice: 'Cannot create item' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_trade 

    bidding_with = Item.find(params[:bid_id])
    
      if @item.trade_established && bidding_with.trade_established
        respond_to do |format|
          #format.html { render @item }
          format.html { redirect_to @item, alert: "failed to bid #{@item.name} because items has been traded" }
          format.json { render json: @item.errors, status: :unprocessable_entity}
        end
        return
      end

    @item.bid_by << bidding_with

    if bidding_with.bid_by.include?(@item)
      @item.trade_established = true
      bidding_with.trade_established = true
      unless @item.save && bidding_with.save
        bidding_with.trade_established = false
        respond_to do |format|
          # refresh page with error
          format.html { redirect_to @item, alert: "Cannot establish trade" }
          format.json { render json: @item.errors, status: :unprocessable_entity}
        end
        return
      end
    end
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: "Sucessfully bid #{bidding_with.name} for #{@item.name}" }
        format.json { render :show, status: :ok, location: @item }
        
      else 
        format.html { redirect_to @item, alert: 'Some unknown error' }
        format.json { render json: @item.errors, status: :unprocessable_entity}
      end
    end
   
  end

  def cancel_bid
    bidding_with = Item.find(params[:bid_id])
    @item.bid_by.delete(bidding_with)
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: "Sucessfully cancelled #{bidding_with.name} for #{@item.name}" }
        format.json { render :show, status: :ok, location: @item }
        
      else 
        format.html { render @item }
        format.json { render json: @item.errors, status: :unprocessable_entity}
      end
    end
   
  end

  def delete_image_attachment
    @image = ActiveStorage::Attachment.find(params[:image_id])
    @image.purge_later
    redirect_to Item.find(params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:category, :name, :description, images: [])
    end

    def has_not_been_traded_assertion
      if @item.trade_established 
        respond_to do |format|
          format.html { redirect_to @item, alert: 'The item has been traded. You cannot modify it'}
          format.html { render json: @item.errors, status: :unprocessable_entity }
        end
      end
    end

    def bid_has_not_been_traded_assertion
      if params[:bid_id].present?
        item = Item.find(params[:bid_id])
        if item.trade_established 
          respond_to do |format|
            format.html { redirect_to item, alert: 'The item has been traded. You cannot modify it'}
            format.html { render json: item.errors, status: :unprocessable_entity }
          end
        end
      end
    end

end

app/helpers/items_helper.rb
module ItemsHelper
    def item_sort(all_item, sort_by, rev=false)
        # all_item is of type Item.all
        # sort_by is a string
        # rev is a boolean to select if the list is reversed
        if sort_by == 'popularity'
            all_item = all_item.left_outer_joins(:bid_by)
                .group('items.id')
                .order("1 #{rev ? 'DESC' : 'ASC'}")
                .select('COUNT(bid_bies_items.id) AS popularity, items.*')
        else 
            all_item = all_item.order(sort_by => rev ? :desc : :asc)
        end
    end
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div class="alert alert-danger col-md-6 offset-md-3">">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>
    </div>
    <div class="text-danger col-md-6 offset-md-3">
      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group col-md-4 offset-md-4">
    <%= form.text_field :category, id: :item_category, placeholder: "Category", class: "form-control", :required => true %>
  </div>

  <div class="field form-group col-md-4 offset-md-4">
    <%= form.text_field :name, id: :item_name, placeholder: "Name", class: "form-control", :required => true %>
  </div>

  <div class="field form-group col-md-4 offset-md-4">
    <%= form.text_area :description, id: :item_description, placeholder: "Description", class: "form-control" %>
  </div>

  <div class="form-group col-md-4 offset-md-4">
    <% if !@item.images.empty? %>
      <% @item.images.each do |image| %>
        <%= image_tag(image, style: 'height:100px;width:auto;') %>
        <button class="btn"><%= link_to 'Remove', delete_image_attachment_item_url(image_id: image.id),
                  method: :delete,
                  data: { confirm: 'Are you sure?' }, class: "btn btn-outline-secondary" %></button>
      <% end %>
    <% end %>
  </div>
  
  <div class="field">
    <%= form.label :user_id, style: "display: none;" %>
    <%= form.text_field :user_id, :readonly => true, class: "form-control", style: "display: none;"  %>
    <!--
    <%= form.number_field :user_id, id: :item_user_id %>
    -->
  </div>
  <div class="text-center">
    <div class="fileinput fileinput-new" data-provides="fileinput">
      <span class="btn btn-outline-secondary btn-file">
        <span class="fileinput-new">Select files</span>
        <span class="fileinput-exists">Change</span>
        <%= form.file_field :images, multiple: true, accept: "image/png, image/gif, image/jpeg"%>
      </span>
      <span class="fileinput-exists"> Files added </span>
    </div>
  </div>
  <div class="actions text-center mt-2">
    <%= form.submit :Submit, class: "btn btn-outline-primary" %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1 class="text-center">Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p>
  <div class="text-center">
    <button class= "btn btn-outline-secondary dropdown-toggle mx-2" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Sort By
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
      <li><%= link_to "Name", {:order => session[:order], :sort => "name",}, class: "dropdown-item" %></li>
      <li><%= link_to "Category", {:order => session[:order], :sort => "category",}, class: "dropdown-item" %></li>
      <li><%= link_to "Date", {:order => session[:order], :sort => "created_at",}, class: "dropdown-item" %></li>
      <li><%= link_to "Popularity", {:order => session[:order], :sort => "popularity",}, class: "dropdown-item" %></li>
    </div>
    <% if params["sort"].present? %>
      <% if params["order"] == "desc" %>
        <button  class= "btn px-2 py-0" aria-haspopup="true" aria-expanded="false"><%= link_to "Ascending", {:order => "asc", :sort => params["sort"],},  class: "btn btn-outline-secondary" %></button>
      <% end %>
      <% if params["order"] == "asc" %>
        <button class="btn px-2 py-0" aria-haspopup="true" aria-expanded="false"><%= link_to "Descending", {:order => "desc", :sort => params["sort"],}, class: "btn btn-outline-secondary" %></button>
      <% end %>
    <% end %>
    <button class="btn px-2 py-0" aria-haspopup="true" aria-expanded="false"><%= link_to 'New Item', new_item_path, class: "btn btn-outline-primary" %></button>
  </div>
</p>

<div class="card" style="width: 100%;">
  <div class="text-center card-header bg-light navbar-brand mr-0">
    Items
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
      <% @items.each do |item| %>
        <% cache(item) do %>
          <a href="/items/<%= item.id %>" class="text-dark" style="text-decoration: none">
            <div class="container">
              <div class="card mb-3 col-md-6 offset-md-3 pl-0 pr-0">
                <div class="row no-gutters">
                  <div class="col-md-4">
                    <% if !item.images.empty? %>
                      <div id="MyCarousel" class="carousel slide carousel-fade" data-ride="carousel">
                        <div class="carousel-inner" role="listbox">
                          <div class="carousel-item active">
                            <%= image_tag(item.images.first, style: 'height: 100%; width: 100%; object-fit: contain') %>
                          </div>
                          <% item.images.drop(1).each do |photo| %>
                            <div class="carousel-item">
                              <%= image_tag(photo, style: 'height: 100%; width: 100%; object-fit: contain') %>
                            </div>
                          <% end %>
                        </div>
                        <ol class="carousel-indicators">
                          <% item.images.each_with_index do |photo, n| %>
                            <li data-target='#MyCarousel' data-slide-to="#{n}" class="#{'active' if n == 0}"></li>
                          <% end %>
                        </ol>
                      </div>
                    <% end %>
                  </div>
                  <div class="col-md-8">
                    <div class="card-body">
                      <% provide(:title, item.name) %>
                      <h4 class="card-title mt-2"><%= item.name %></h5>
                      <p class="card-text">Category: <%= item.category %></p>
                      <% owner = User.find(item.user_id) %>
                      <% cache (owner) do %>
                        <p class="card-text">User: <%= owner.name %></p>
                        <p class="card-text">Description: <%= item.description%></p>
                        <p class="card-text">Date Added: <%= item.created_at %></p>
                        <% pplrt=item.popularity%>
                        <% cache (pplrt) do %>
                          <p class="card-text">Popularity: <%= pplrt %></p>
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </a>
        <% end %>
      <% end %> 
    </li>
  </ul>

  <% if @prev_page != nil %>
    <%= link_to "#{@prev_page}", items_path(page_num: @prev_page) %>
  <% end %>
  
  <span> <%= params['page_num'] || 1 %> </span>

  <% if @next_page != nil %>
    <%= link_to "#{@next_page}", items_path(page_num: @next_page) %>
  <% end %>
</div>

app/views/items/new.html.erb
<h1 class="mt-5 text-center">New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<div class="card mt-4 col-md-6 offset-md-3 pl-0 pr-0">
  <div class="row no-gutters">
    <div class="col-md-4">
      <% if !@item.images.empty? %>
        <div id="MyCarousel" class="carousel slide carousel-fade" data-ride="carousel">
          <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
              <%= image_tag(@item.images.first, style: 'height: 100%; width: 100%; object-fit: contain') %>
            </div>
            <% @item.images.drop(1).each do |photo| %>
              <div class="carousel-item">
                <%= image_tag(photo, style: 'height: 100%; width: 100%; object-fit: contain') %>
              </div>
            <% end %>
          </div>
          <ol class="carousel-indicators">
            <% @item.images.each_with_index do |photo, n| %>
              <li data-target='#MyCarousel' data-slide-to="#{n}" class="#{'active' if n == 0}"></li>
            <% end %>
          </ol>
        </div>
      <% end %>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <% provide(:title, @item.name) %>
        <h4 class="card-title mt-2"><%= @item.name %></h5>
        <p class="card-text">Category: <%= @item.category %></p>
        <% owner = User.find(@item.user_id) %>
        <p class="card-text">User: <%= owner.name %></p>
        <p class="card-text">Description: <%= @item.description%></p>
        <p class="card-text">Date Added: <%= @item.created_at %></p>
        <%= pplrt = @item.popularity %>
        <%cache(pplrt) do %>
        <p class="card-text">Popularity: <%= pplrt %></p>
        <%end%>
      </div>
    </div>
  </div>
</div>

<% if @item.trade_established %>
  <p class="text-center mt-3">This item has been traded! You came too late lah.</p>
  <p class="text-center">
    It was traded with <%= link_to "\"#{@traded_item.name}\"", @traded_item %>
  </p>
  
<% else %>
  <% if logged_in? %>
    <% if @item.user_id == current_user.id %>
      <p>
        <div class="card mt-4 pl-0 pr-0"> 
          <div class="text-center card-header bg-light navbar-brand mr-0">
            Other people want to trade <%=@item.name%> with
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              <% @item.bid_by.each do |item| %>
                <a href="/items/<%= item.id %>" class="text-dark" style="text-decoration: none">
                  <div class="container">
                    <div class="card mb-3 col-md-6 offset-md-3 pl-0 pr-0">
                      <div class="row no-gutters">
                        <div class="col-md-4">
                          <% if !item.images.empty? %>
                            <div id="MyCarousel" class="carousel slide carousel-fade" data-ride="carousel">
                              <div class="carousel-inner" role="listbox">
                                <div class="carousel-item active">
                                  <%= image_tag(item.images.first, style: 'height: 100%; width: 100%; object-fit: contain') %>
                                </div>
                                <% item.images.drop(1).each do |photo| %>
                                  <div class="carousel-item">
                                    <%= image_tag(photo, style: 'height: 100%; width: 100%; object-fit: contain') %>
                                  </div>
                                <% end %>
                              </div>
                              <ol class="carousel-indicators">
                                <% item.images.each_with_index do |photo, n| %>
                                  <li data-target='#MyCarousel' data-slide-to="#{n}" class="#{'active' if n == 0}"></li>
                                <% end %>
                              </ol>
                            </div>
                          <% end %>
                        </div>
                        <div class="col-md-8">
                          <div class="card-body">
                           <% provide(:title, item.name) %>
                            <h4 class="card-title mt-2"><%= item.name %></h5>
                            <p class="card-text">Category: <%= item.category %></p>
                            <% owner = User.find(item.user_id) %>
                            <p class="card-text">User: <%= owner.name %></p>
                            <p class="card-text">Description: <%= item.description%></p>
                            <p class="card-text">Date Added: <%= item.created_at %></p>
                            <p class="card-text">Popularity: <%= item.popularity %></p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </a>
              <% end %>
            </li>
          </ul>
        </div>
      </p>
    <% else %>
      <p>
        <div class="card mt-4 pl-0 pr-0">
          <div class="text-center card-header bg-light navbar-brand mr-0"> 
            Select items you want to trade for <%=@item.name%>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              <% current_user.items.each do |item| %>
                <% unless item.trade_established %>
                    <div class="container">
                      <div class="card mb-3 col-md-6 offset-md-3 pl-0 pr-0">
                        <div class="row no-gutters">
                          <div class="col-md-4">
                            <% if !item.images.empty? %>
                              <div id="MyCarousel" class="carousel slide carousel-fade" data-ride="carousel">
                                <div class="carousel-inner" role="listbox">
                                  <div class="carousel-item active">
                                    <%= image_tag(item.images.first, style: 'height: 100%; width: 100%; object-fit: contain') %>
                                  </div>
                                  <% item.images.drop(1).each do |photo| %>
                                    <div class="carousel-item">
                                      <%= image_tag(photo, style: 'height: 100%; width: 100%; object-fit: contain') %>
                                    </div>
                                  <% end %>
                                </div>
                                <ol class="carousel-indicators">
                                  <% item.images.each_with_index do |photo, n| %>
                                    <li data-target='#MyCarousel' data-slide-to="#{n}" class="#{'active' if n == 0}"></li>
                                  <% end %>
                                </ol>
                              </div>
                            <% end %>
                          </div>
                          <div class="col-md-8">
                            <div class="card-body pb-0">
                              <% provide(:title, item.name) %>
                              <h4 class="card-title"><%= item.name %></h5>
                              <p class="card-text">Category: <%= item.category %></p>
                              <% owner = User.find(item.user_id) %>
                              <p class="card-text">User: <%= owner.name %></p>
                              <p class="card-text">Description: <%= item.description%></p>
                              <p class="card-text">Date Added: <%= item.created_at %></p>
                              <p class="card-text">Popularity: <%= item.popularity %></p>
                            </div>
                            <button class="btn ml-3 px-1" aria-haspopup="true" aria-expanded="false"><%= link_to 'Show', item, class: "btn btn-outline-primary" %></button>
                            <% if !@item.bid_by.include?(item) %>
                              <button class="btn px-1" aria-haspopup="true" aria-expanded="false"><%= link_to 'Trade', add_trade_item_path(@item, :bid_id => item.id), method: :post, class:"btn btn-outline-primary"  %></button>
                            <% else %>
                              <button class="btn px-1" aria-haspopup="true" aria-expanded="false"><%= link_to 'Cancel', cancel_bid_item_path(@item, :bid_id => item.id), method: :post, class: "btn btn-outline-danger" %></button>
                            <% end %>
                          </div>
                        </div>
                      </div>
                    </div>
                 
                <% end %>
              <% end %>
            </li>
          </ul>
        </div>
      </p>
    <% end %>
  <% end %> 
<% end %>

<div class="text-center">
  <% if logged_in? && @item.user_id == current_user.id %>
    <button class="btn px-0"><%= link_to 'Edit', edit_item_path(@item), class: "btn btn-outline-primary"%></button>
  <% end %> 
  <button class="btn"><%= link_to 'Back', session[:return_to], class: "btn btn-outline-primary" %></button>
</div>