config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root to: 'pages#homepage'

  resources :items do
    post '/trade/:bid_id', on: :member, to: 'items#add_trade', as: 'add_trade'
    post '/cancel/:bid_id', on: :member, to: 'items#cancel_bid', as: 'cancel_bid'
    member do
      delete :delete_image_attachment
    end
  end

  get 'users/new'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header>
  <div>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "SwapSpace", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to "Home", root_path, class: "#{current_page?(root_path)? "nav-link active" : "nav-link"}" %> 
      </li>
      <li class="nav-item">
        <%= link_to "Items", '/items', class: "#{current_page?(items_path)? "nav-link active" : "nav-link"}" %>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Profile", current_user, class: "dropdown-item"%>
          <%= link_to "Log Out", logout_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Log In", login_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>
  </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Swapspace</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div>
      <% flash.each do |message_type, message| %>
        <div class="text-center col-md-6 mt-4 offset-md-3 alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    </div>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>